# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_photo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438'},
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='photos', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
