# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-08 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170803_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='article_pics', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
        ),
    ]
