# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170808_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 youtube video')),
            ],
            options={
                'db_table': 'videos',
                'verbose_name': '\u0412\u0438\u0434\u043e\u0441',
                'verbose_name_plural': '\u0412\u0438\u0434\u043e\u0441\u044b',
            },
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
