# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170924_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='link',
        ),
    ]
